name: Terraform Apply (Manual / Protected)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest

    environment: prod

    defaults:
      run:
        working-directory: Projects/terraform-web-service/terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (no backend)
        run: terraform init -backend=false

      - name: Terraform Plan (no refresh)
        run: |
          terraform plan \
            -refresh=false \
            -var-file=dev.tfvars \
            -var="my_ip=127.0.0.1/32" \
            -input=false \
            -no-color

      - name: Apply step (disabled on purpose)
        run: |
          echo "Apply is intentionally disabled"
          echo "We will enable real apply only after CI IAM + secrets are set up."