name: Terraform CI

on:
  push:
    paths:
      - 'projects/terraform-web-service/**'
  pull_request:
    paths:
      - 'projects/terraform-web-service/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: projects/terraform-web-service/terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.4
      - name: Disable backend for CI
        run: |
          if [ -f backend.tf ]; then
            mv backend.tf backend.tf.disabled
          fi

      - name: Terraform Init (no backend)
        run: terraform init -backend=false

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate